// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Source.Models;

public partial class Playlist
{
    public string Id { get; set; } = null!;

    public string? Name { get; set; }

    public string Link { get; set; } = null!;
}