// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Source.Models;

public partial class SpotifyManagerDbContext : DbContext
{
    public SpotifyManagerDbContext(DbContextOptions<SpotifyManagerDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Playlist> Playlist { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Playlist>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("ID");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}